### ISSUE TITLE
[FEATURE] Add basic login to admin panel

### ISSUE THREAD

**Issue by FinecoFinit** [Duosion/starpoint#30]
Want to host it, but exposing admin panel to everyone is insecure

**Comment by 121GWJolt** [comment]
If you were to really want to do it, you could probably just set it up behind an auth portal hosted on the reverse proxy, like [this repo](https://github.com/vouch/vouch-proxy) allows, and get better security than anything built into the app would actually support. The auth is configured per server entry, so it wouldn't affect the proxy itself.

You'd need something like nginx to do the SSL redirect anyway.

**Comment by 121GWJolt** [comment]
If you were to really want to do it, you could probably just set it up behind an auth portal hosted on the reverse proxy, like [this repo](https://github.com/vouch/vouch-proxy) allows, and get really good security without having to host the auth yourself and worry about security. The auth is configured per server entry, so it wouldn't affect the proxy itself.

You'd need something like nginx to do the SSL redirect anyway.

**Comment by FinecoFinit** [comment]
@121GWJolt game app makes calls on na.wdfp.kakaogames.com, where admin panel hosted, best solution here as I see is to place admin panel on other url path

**Comment by 121GWJolt** [comment]
If something has to be put on another path, I feel like in that case it'd be cleaner to change where wdfp goes, tbh, and put that on a subpath like the rest of the stuff. I haven't read the source entirely, but it at least looks like it wouldn't be the worst thing in the world to accomplish. Would also still be fine behind the reverse proxy since making the subfolder available wouldn't offer a way to access the parent.

And we wouldn't need to worry about multiple user accounts for uploading saves & stuff since this is really for private hosting in its current state.

**Comment by 121GWJolt** [comment]
If something has to be put on another path, I feel like in that case it'd be cleaner to change where wdfp goes, tbh, and put that on a subpath like the rest of the stuff. I haven't read the source entirely, but it at least looks like it wouldn't be the worst thing in the world to accomplish. Would also still be fine behind the reverse proxy since making the subfolder available wouldn't offer a way to access the parent.

Plus, the auth doesn't really need to be in the site itself since the program in its current incarnation doesn't really have any incentive to not be hosted locally in small groups, especially with the DNS server requirement.

How were you going to host it? I guess you're not using a private VPN if you need an auth portal.

**Comment by FinecoFinit** [comment]
look at this [mitm-redirect-traffic.py](https://github.com/Duosion/starpoint/blob/main/scripts/mitm-redirect-traffic.py).
I already host starpoint, the only thing you have to do is to set my dns server on your phone to access the starpoint

**Comment by 121GWJolt** [comment]
Wait you're using mitmproxy over the Internet? I guess it's not in Wireguard mode, then since you're only talking about changing the DNS?

**Comment by FinecoFinit** [comment]
I use docker, traefik(reverse proxy) and adguardhome(dns)

**Comment by 121GWJolt** [comment]
Oh okay, yeah I can understand that setup. Then I guess you'd probably want [this one](https://doc.traefik.io/traefik/middlewares/http/basicauth/) instead.

**Comment by 121GWJolt** [comment]
Okay, so I don't use traefik, but based on their route matching docs, you can likely use the following to match the locations for just the game while preventing the (currently-known) starpoint pages from being accessible. While this won't account for adding further pages, at the very least it should serve as a short term solution.

Your na.wdfp rule:
```go
Host(`na.wdfp.kakaogames.com`) && PathRegexp(`^\/(?:.*\S.*)+$`) && !PathRegExp(`(?i)^\/(?:player|server).*$`)
```
This will match everything *except* root and current starpoint-specific route modules (from what I gather according to traefik's docs page, anyway). Seems Go doesn't support lookarounds.

Your starpoint admin rule:
```go
Host(`your-local-hostname-for-starpoint-here`)
```

Then just put an SSL on the starpoint url and add the auth module to it.

LMK if these work!

**Comment by 121GWJolt** [comment]
@FinecoFinit

Okay so actually...
Turns out every wdfp root goes through /latest/api/index.php

So you can just do:

```go
Host(`na.wdfp.kakaogames.com`) && PathPrefix(`/latest/api/index.php`)
```

**Comment by 121GWJolt** [comment]
For extra security, you can probably also use
```go
&& ClientIP(`192.168.1.0/24`)
```
on any of these services with respective local IPs to do extra blocking of unauthorized access.

**Comment by FinecoFinit** [comment]
@121GWJolt 
> ```go
> Host(`na.wdfp.kakaogames.com`) && PathPrefix(`/latest/api/index.php`)
> ```
Damn, It's working

**Comment by 121GWJolt** [comment]
Alright, glad to know! Hope it keeps your instance guarded from outside access!

For future reference, turns out it's also possible to exclude paths and make a wildcard match for "every path but root" using `PathRegex`, so even if this turns out to not be everything, the rules are flexible enough to manage the paths that way instead.

I guess this issue could be considered closed, then?

**Comment by 121GWJolt** [comment]
@FinecoFinit  ^?
